# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, length: str=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param name: The name of this InlineResponse2002.  # noqa: E501
        :type name: str
        :param length: The length of this InlineResponse2002.  # noqa: E501
        :type length: str
        """
        self.swagger_types = {
            'name': str,
            'length': str
        }

        self.attribute_map = {
            'name': 'name',
            'length': 'length'
        }

        self._name = name
        self._length = length

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse2002.

        the name of queue  # noqa: E501

        :return: The name of this InlineResponse2002.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse2002.

        the name of queue  # noqa: E501

        :param name: The name of this InlineResponse2002.
        :type name: str
        """

        self._name = name

    @property
    def length(self) -> str:
        """Gets the length of this InlineResponse2002.

        the length of queue  # noqa: E501

        :return: The length of this InlineResponse2002.
        :rtype: str
        """
        return self._length

    @length.setter
    def length(self, length: str):
        """Sets the length of this InlineResponse2002.

        the length of queue  # noqa: E501

        :param length: The length of this InlineResponse2002.
        :type length: str
        """

        self._length = length
